version: "3.8"

x-backend-config: &backend-config
  env_file:
    - .env
  build: .
  environment:
    - DATABASE_URL=postgres://optifino:optifino@db_optifino/optifino
    - PYTHONUNBUFFERED=1
    - CLOUDAMQP_URL=amqp://admin:mypass@rabbit:5672//

x-worker-config: &worker-config
  <<: *backend-config
  depends_on:
    - rabbit_optifino
    - db_optifino
  volumes:
    - ./:/srv

volumes:
  pg-data:
  redis-data:

services:
  db_optifino:
    image: postgres:14-alpine
    container_name: db_optifino
    environment:
      - POSTGRES_DB=optifino
      - POSTGRES_USER=optifino
      - POSTGRES_PASSWORD=optifino
    shm_size: 512mb
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbit_optifino:
    container_name: rabbit_optifino
    hostname: rabbit
    image: rabbitmq:3.7.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
      - "15673:15672"

  redis_optifino:
    container_name: redis_optifino
    image: redis:5.0.4-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  backend:
    <<: *backend-config
    container_name: backend
    expose:
      - ${PORT}
    depends_on:
      - db_optifino
      - redis_optifino
      - rabbit_optifino
    volumes:
      - ./:/srv
    ports:
      - "8000:${PORT}"
    command: uvicorn optifino.asgi:app --host 0.0.0.0 --port ${PORT} --log-level=info

  worker:
    <<: *worker-config
    container_name: worker
    depends_on:
      - rabbit_optifino
      - db_optifino
    command: celery -A optifino worker -Q normal -c 3 --loglevel=info
