# Generated by Django 4.1.7 on 2023-03-27 16:16

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_url', models.URLField()),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'),
                             ('failed', 'Failed')], default='pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('parent',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.link')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.task')),
            ],
        ),
    ]
